name: CI

on: push

env:
  DOWNLOAD_TOOL: curl -fLOSs --retry 2 --retry-delay 60

  QT_VERSION: 5.15.2
  ZLIB_VERSION: 1.2.11
  BZIP_VERSION: 1.0.8
  NASM_VERSION: 2.15.05
  YASM_VERSION: 1.3.0
  LAME_VERSION: "3.100"
  OPUS_VERSION: v1.3.1
  FFMPEG_VERSION: "5.0"
  OPENEXR_VERSION: "v3.1.5"
  OCIO_VERSION: v2.2.0
  TIFF_VERSION: 4.3.0
  JPEGTURBO_VERSION: 2.1.3
  GIF_VERSION: 5.2.1
  LIBRAW_VERSION: 0.20.2
  OIIO_VERSION: v2.3.19.0
  LIBPNG_VERSION: v1.6.37
  OPENSSL_VERSION: "OpenSSL_1_1_1s"
  X265_VERSION: 3.5
  LIBWEBP_VERSION: v1.2.2
  LIBVPX_VERSION: v1.11.0
  PORTAUDIO_VERSION: v19.7.0
  OTIO_VERSION: "v0.15"
  MODPLUG_VERSION: b7660b1d4fdec9ead25e8716c14cf77809861656

jobs:
  mac:
    strategy:
      matrix:
        include:
          - arch: x86_64
            os: macos-11.0
          - arch: arm64
            os: macos-11.0
    name: macOS (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    env:
      ARCH: ${{ matrix.arch }}
      CFLAGS: "-mmacosx-version-min=10.14 -arch ${{ matrix.arch }}"
      CXXFLAGS: "-mmacosx-version-min=10.14 -arch ${{ matrix.arch }}"
      LDFLAGS: "-mmacosx-version-min=10.14 -arch ${{ matrix.arch }}"
      MACOSX_DEPLOYMENT_TARGET: 10.14
      BUILD_TYPE: Release
      CMAKE_OSX_ARCHITECTURES: ${{ matrix.arch }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Create install destination
        shell: bash
        run: |
          sudo mkdir /opt/olive-editor
          sudo chmod 777 /opt/olive-editor
          echo "INSTALL_DIR=/opt/olive-editor" >> $GITHUB_ENV
          echo -e "/opt/olive-editor\n/opt/olive-editor/lib\n/opt/olive-editor/include\n$(cat $GITHUB_PATH)" > $GITHUB_PATH

      - name: Uninstall existing brew packages
        run: |
          while [[ `brew list | wc -l` -ne 0 ]]; do
            for EACH in `brew list`; do
              brew uninstall --force --ignore-dependencies $EACH
            done
          done

      - name: Install Tools
        shell: bash
        run: |
          brew install cmake ninja nasm yasm pkg-config

      - name: Build OpenSSL
        shell: bash
        working-directory: ${{ runner.workspace }}
        run: |
          git clone --branch $OPENSSL_VERSION --depth 1 https://github.com/openssl/openssl.git
          cd openssl
          perl Configure darwin64-$ARCH-cc --prefix="$INSTALL_DIR" --openssldir="$INSTALL_DIR"
          make depend
          make install

      - name: Build libx265
        shell: bash
        working-directory: ${{ runner.workspace }}
        run: |
          git clone --branch $X265_VERSION --depth 1 https://bitbucket.org/multicoreware/x265_git
          cd x265_git
          mkdir b
          cd b

          if [ "$ARCH" == "arm64" ]
          then
            # We set ENABLE_ASSEMBLY to OFF because their code is fucked and I can't figure it out.
            # One day it should be re-enabled for performance probably.
            cmake ../source -G "Ninja" -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" -DCMAKE_OSX_ARCHITECTURES=$ARCH -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/x265-arm64-crosscompile.cmake -DENABLE_ASSEMBLY=OFF
          else
            cmake ../source -G "Ninja" -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR"
          fi

          ninja
          ninja install

      - name: Build PortAudio
        shell: bash
        working-directory: ${{ runner.workspace }}
        run: |
          git clone --branch $PORTAUDIO_VERSION --depth 1 https://github.com/PortAudio/portaudio.git
          cd portaudio
          mkdir b
          cd b
          cmake .. -G "Ninja" -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_OSX_ARCHITECTURES=$ARCH
          ninja
          ninja install

      - name: Build libx264
        shell: bash
        working-directory: ${{ runner.workspace }}
        run: |
          git clone --depth 1 https://code.videolan.org/videolan/x264.git
          cd x264
          ./configure --prefix="$INSTALL_DIR" --enable-shared --disable-cli --host=$ARCH-darwin
          make
          make install

      - name: Build libmp3lame
        shell: bash
        working-directory: ${{ runner.workspace }}
        run: |
          $DOWNLOAD_TOOL https://downloads.sourceforge.net/project/lame/lame/$LAME_VERSION/lame-$LAME_VERSION.tar.gz
          tar xzf lame-$LAME_VERSION.tar.gz
          cd lame-$LAME_VERSION

          # Patch to remove legacy undefined export
          sed -i '' '/lame_init_old/d' include/libmp3lame.sym

          if [ "$ARCH" == "arm64" ]
          then
            HOST=aarch64
          else
            HOST=x86_64
          fi

          ./configure --enable-shared --disable-static --prefix="$INSTALL_DIR" --host=$HOST-apple-darwin CFLAGS="-arch $ARCH"
          make
          make install

      - name: Build libvpx
        shell: bash
        working-directory: ${{ runner.workspace }}
        run: |
          git clone --branch $LIBVPX_VERSION --depth 1 https://chromium.googlesource.com/webm/libvpx.git
          cd libvpx
          ./configure --prefix="$INSTALL_DIR" --disable-examples --disable-unit-tests --enable-vp9-highbitdepth --as=yasm --target=$ARCH-darwin20-gcc
          make
          make install

      - name: Build libopus
        shell: bash
        working-directory: ${{ runner.workspace }}
        run: |
          git clone --branch $OPUS_VERSION --depth 1 https://github.com/xiph/opus.git
          cd opus
          mkdir build
          cd build
          cmake .. -G "Ninja" -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_OSX_ARCHITECTURES=$ARCH
          ninja
          ninja install

      - name: Build libmodplug
        shell: bash
        working-directory: ${{ runner.workspace }}
        run: |
          git clone https://github.com/Konstanty/libmodplug.git
          cd libmodplug
          git checkout $MODPLUG_VERSION

          # Fix rpath on macOS
          git apply $GITHUB_WORKSPACE/modplug-set-rpath.diff

          mkdir build
          cd build
          cmake .. -G Ninja -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" -DBUILD_SHARED_LIBS=ON -DCMAKE_OSX_ARCHITECTURES=$ARCH
          ninja
          ninja install

      - name: Build FFmpeg
        shell: bash
        working-directory: ${{ runner.workspace }}
        run: |
          $DOWNLOAD_TOOL https://www.ffmpeg.org/releases/ffmpeg-$FFMPEG_VERSION.tar.xz
          tar xf ffmpeg-$FFMPEG_VERSION.tar.xz
          cd ffmpeg-$FFMPEG_VERSION
          export PKG_CONFIG_PATH=$INSTALL_DIR/lib/pkgconfig

          if [ "$ARCH" == "arm64" ]
          then
            EXTRA_FFMPEG_ARGS="--enable-cross-compile"
          fi

          ./configure \
            --arch=$ARCH \
            --target-os=darwin \
            --extra-cflags="-I$INSTALL_DIR/include -arch $ARCH" \
            --extra-ldflags="-L$INSTALL_DIR/lib -arch $ARCH -headerpad_max_install_names" \
            --prefix=$INSTALL_DIR \
            --enable-shared \
            --disable-static \
            --disable-programs \
            --enable-gpl \
            --enable-version3 \
            --enable-libmp3lame \
            --enable-libopus \
            --enable-libvpx \
            --enable-libx264 \
            --enable-libx265 \
            --enable-bzlib \
            --enable-libmodplug \
            $EXTRA_FFMPEG_ARGS \
            --disable-avx512
          make
          make install
          cd ..
          rm -rf ffmpeg-$FFMPEG_VERSION ffmpeg-$FFMPEG_VERSION.tar.xz

      - name: Build Imath
        shell: bash
        working-directory: ${{ runner.workspace }}
        run: |
          # Use the same version as OpenEXR to keep them synchronized
          git clone --branch $OPENEXR_VERSION --depth 1 https://github.com/AcademySoftwareFoundation/Imath.git
          cd Imath
          mkdir build
          cd build
          cmake .. -G "Ninja" -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DPYTHON=OFF -DCMAKE_OSX_ARCHITECTURES=$ARCH -DBUILD_SHARED_LIBS=ON
          ninja
          ninja install

      - name: Build OpenEXR
        shell: bash
        working-directory: ${{ runner.workspace }}
        run: |
          git clone --branch $OPENEXR_VERSION --depth 1 https://github.com/AcademySoftwareFoundation/openexr.git
          cd openexr
          mkdir build
          cd build
          cmake .. -G "Ninja" -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DPYILMBASE_ENABLE=OFF -DOPENEXR_VIEWERS_ENABLE=OFF -DCMAKE_OSX_ARCHITECTURES=$ARCH -DCMAKE_PREFIX_PATH="$INSTALL_DIR"
          ninja
          ninja install

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Build OpenColorIO
        shell: bash
        working-directory: ${{ runner.workspace }}
        run: |
          git clone --branch $OCIO_VERSION --depth 1 https://github.com/AcademySoftwareFoundation/OpenColorIO.git
          cd OpenColorIO
          mkdir build
          cd build
          cmake .. -G "Ninja" -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DOCIO_BUILD_PYTHON=OFF -DOCIO_BUILD_APPS=OFF -DOCIO_BUILD_TESTS=OFF -DOCIO_BUILD_GPU_TESTS=OFF -DOCIO_BUILD_DOCS=OFF -DCMAKE_OSX_ARCHITECTURES=$ARCH -DCMAKE_PREFIX_PATH="$INSTALL_DIR"
          ninja
          ninja install

      - name: Build Boost
        shell: bash
        working-directory: ${{ runner.workspace }}
        run: |
          $DOWNLOAD_TOOL https://boostorg.jfrog.io/artifactory/main/release/1.77.0/source/boost_1_77_0.tar.gz
          tar xzf boost_1_77_0.tar.gz
          cd boost_1_77_0
          ./bootstrap.sh

          if [ "$ARCH" == "arm64" ]
          then
            CPU=arm
          else
            CPU=x86
          fi

          ./b2 install address-model=64 architecture=$CPU variant=release link=shared cxxflags="-arch $ARCH" linkflags="-arch $ARCH" --prefix=$INSTALL_DIR --with-filesystem --with-system --with-thread

      - name: Build libpng
        shell: bash
        working-directory: ${{ runner.workspace }}
        run: |
          git clone --branch $LIBPNG_VERSION --depth 1 https://github.com/glennrp/libpng.git
          cd libpng
          git apply $GITHUB_WORKSPACE/png-osx-arm64.patch
          mkdir build
          cd build
          cmake .. -G "Ninja" -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_OSX_ARCHITECTURES=$ARCH -DPNG_ARM_NEON=on
          ninja
          ninja install

      - name: Build libjpeg-turbo
        shell: bash
        working-directory: ${{ runner.workspace }}
        run: |
          $DOWNLOAD_TOOL https://downloads.sourceforge.net/project/libjpeg-turbo/$JPEGTURBO_VERSION/libjpeg-turbo-$JPEGTURBO_VERSION.tar.gz
          tar xzf libjpeg-turbo-$JPEGTURBO_VERSION.tar.gz
          cd libjpeg-turbo-$JPEGTURBO_VERSION
          mkdir build
          cd build
          cmake .. -G "Ninja" -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_OSX_ARCHITECTURES=$ARCH
          ninja
          ninja install

      - name: Build libwebp
        shell: bash
        working-directory: ${{ runner.workspace }}
        run: |
          git clone --branch $LIBWEBP_VERSION --depth 1 https://chromium.googlesource.com/webm/libwebp
          cd libwebp
          mkdir build
          cd build
          cmake .. -G "Ninja" -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_OSX_ARCHITECTURES=$ARCH \
            -DWEBP_BUILD_ANIM_UTILS=OFF \
            -DWEBP_BUILD_CWEBP=OFF \
            -DWEBP_BUILD_DWEBP=OFF \
            -DWEBP_BUILD_GIF2WEBP=OFF \
            -DWEBP_BUILD_IMG2WEBP=OFF \
            -DWEBP_BUILD_VWEBP=OFF \
            -DWEBP_BUILD_EXTRAS=OFF \
            -DWEBP_BUILD_WEBPINFO=OFF \
            -DWEBP_BUILD_WEBPMUX=OFF
          ninja
          ninja install

      - name: Build libtiff
        shell: bash
        working-directory: ${{ runner.workspace }}
        run: |
          $DOWNLOAD_TOOL https://download.osgeo.org/libtiff/tiff-$TIFF_VERSION.tar.gz
          tar xzf tiff-$TIFF_VERSION.tar.gz
          cd tiff-$TIFF_VERSION
          mkdir b
          cd b
          cmake .. -G "Ninja" -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_OSX_ARCHITECTURES=$ARCH
          ninja
          ninja install

      - name: Build LibRaw
        shell: bash
        working-directory: ${{ runner.workspace }}
        run: |
          brew install automake libtool
          $DOWNLOAD_TOOL https://www.libraw.org/data/LibRaw-$LIBRAW_VERSION.tar.gz
          tar xzf LibRaw-$LIBRAW_VERSION.tar.gz
          cd LibRaw-$LIBRAW_VERSION
          autoreconf -i

          if [ "$ARCH" == "arm64" ]
          then
            HOST=aarch64
          else
            HOST=x86_64
          fi

          ./configure --disable-lcms --prefix="$INSTALL_DIR" --host=$HOST-apple-darwin
          make
          make install

      - name: Build giflib
        shell: bash
        working-directory: ${{ runner.workspace }}
        run: |
          $DOWNLOAD_TOOL https://downloads.sourceforge.net/project/giflib/giflib-$GIF_VERSION.tar.gz
          tar xzf giflib-$GIF_VERSION.tar.gz
          cd giflib-$GIF_VERSION
          $DOWNLOAD_TOOL https://sourceforge.net/p/giflib/bugs/_discuss/thread/4e811ad29b/c323/attachment/Makefile.patch
          patch Makefile Makefile.patch
          make install CFLAGS="$CFLAGS" LDFLAGS="$LDFLAGS" PREFIX=$INSTALL_DIR
          install_name_tool -id @rpath/libgif.dylib $INSTALL_DIR/lib/libgif.dylib

      - name: Build OpenImageIO
        shell: bash
        working-directory: ${{ runner.workspace }}
        run: |
          git clone --branch $OIIO_VERSION --depth 1 https://github.com/OpenImageIO/oiio.git
          cd oiio

          # HACK: We don't need freetype and it causes linking issues. You can't disable it in OIIO
          #       so we just remove it.
          git apply $GITHUB_WORKSPACE/oiio-remove-freetype.patch

          # HACK: Tries to link with system HEIF and OpenJP, which breaks arm64 cross compiles
          git apply $GITHUB_WORKSPACE/oiio-remove-heif-openjp.patch

          mkdir build
          cd build
          cmake .. -G "Ninja" -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DUSE_PYTHON=OFF -DCMAKE_OSX_ARCHITECTURES=$ARCH \
            -DBoost_ROOT="$INSTALL_DIR" -DTIFF_ROOT="$INSTALL_DIR" -DCMAKE_PREFIX_PATH="$INSTALL_DIR" -DCMAKE_CXX_STANDARD=17
          ninja
          ninja install

      - name: Build OpenTimelineIO
        shell: bash
        working-directory: ${{ runner.workspace }}
        run: |
          git clone --depth 1 --branch $OTIO_VERSION https://github.com/PixarAnimationStudios/OpenTimelineIO.git
          cd OpenTimelineIO

          # Fixes linking on macOS
          git apply $GITHUB_WORKSPACE/otio-remove-install-name-dir.patch

          mkdir build
          cd build
          cmake .. -G "Ninja" -DCMAKE_CXX_STANDARD=17 -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DOTIO_PYTHON_INSTALL=OFF -DCMAKE_OSX_ARCHITECTURES=$ARCH
          ninja
          ninja install

      - name: Build Qt
        shell: bash
        working-directory: ${{ runner.workspace }}
        run: |
          git clone --branch $QT_VERSION --depth 1 https://code.qt.io/qt/qt5.git
          cd qt5
          perl init-repository --module-subset=qtbase,qtsvg,qttools

          cd qtbase
          git apply $GITHUB_WORKSPACE/qt5-include-cgcolorspace.patch

          if [ "$ARCH" == "arm64" ]
          then
            cp -R mkspecs/macx-clang mkspecs/macx-clang-arm64
            echo "QMAKE_APPLE_DEVICE_ARCHS=arm64" >> mkspecs/macx-clang-arm64/qmake.conf
            EXTRA_QT_ARGS="-xplatform macx-clang-arm64"
          fi

          cd ..

          ./configure \
            -opensource -confirm-license -opengl desktop -nomake examples -nomake tests \
            -prefix "$INSTALL_DIR" -release -ssl -openssl-linked \
            -I "$INSTALL_DIR/include" -L "$INSTALL_DIR/lib" \
            $EXTRA_QT_ARGS
          make
          make install
          cd ..

          # Free up space
          rm -rf qt5

      - name: Deploy
        shell: bash
        working-directory: ${{ runner.workspace }}
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TRAVIS_REPO_SLUG: olive-editor/dependencies
          TRAVIS_COMMIT: ${{ github.sha }}
        run: |
          $DOWNLOAD_TOOL https://github.com/probonopd/uploadtool/raw/master/upload.sh
          tar czf "olive-dep-mac-$ARCH.tar.gz" "/opt/olive-editor"
          chmod +x upload.sh
          ./upload.sh "olive-dep-mac-$ARCH.tar.gz"
